# Generated by Django 5.0.1 on 2024-04-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_at']},
        ),
    ]
